Install lxml>=4, <4.4 only for python != 2.7 or < 3.5
Having this in our setup.py causes lots of problems when installing
other packages.  Pip doesn't try to resolve version conflicts.  If it
installs lxml 4.4.1 (latest) as a dependency of some other package, and
then it installs rhaptos.cnxmlutils, it outputs this error message:

```
ERROR: rhaptos-cnxmlutils 1.7.1 has requirement lxml<4.4,>=4, but you'll
have lxml 4.4.1 which is incompatible.
```

We only need to have `lxml>=4, <4.4` for python != 2.7 or < 3.5.